### ISSUE TITLE
problem with polish charset

### ISSUE THREAD

**Issue by ixcesal** [oiv/sortablejs#19]
When we sort text column Polish (special) charset are last, not on right position. For example Letter Ł is after L, not after Z...

**Comment by oiv** [comment]
Hi. You mean Ł **should** sort after L? not after Z?

The sorting happens according the characters unicode values. Where (in decimal) L=76, Z=90 and Ł=321.
Sorts ok in my test based on this.

**Comment by ixcesal** [comment]
In decimal order thats right.
But in alphabetical order in polish it isn't good :(

**Comment by FyiurAmron** [comment]
a) this is not Polish-related, but instead locale-related (does happen in other locales too), and I confirm it does happen with all and any locale-related chars,
b) @oiv it doesn't *sort ok* - actual strings shouldn't and mustn't be compared based on ASCII order, but on the natural ordering of the locale alphabet instead,
c) finally - it can be easily fixed by replacing the code in `sortAlpha` with simply `return a.localeCompare(b);`; done it and the sort works like a charm.

**Comment by ixcesal** [comment]
```
  sort_alpha: function(a,b) {
//    if (a[0]==b[0]) {return 0;}
//    if (a[0]<b[0]) {return -1;}
//    return 1;
return a[0].localeCompare(b[0]);
```

working great :)
thx a lot
